# Generated by Django 4.2.16 on 2024-11-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0003_auto_20241128_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfp_skus',
            name='extra_data',
        ),
    ]
