# Generated by Django 4.2.16 on 2024-12-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0009_alter_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfx',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfxs', to='procurement01.project'),
            preserve_default=False,
        ),
    ]
