# Generated by Django 4.2.16 on 2024-12-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0013_oem_procurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='oem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement01.oem'),
        ),
    ]
