# Generated by Django 4.2.16 on 2024-11-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFP_SKUSpecificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('rfp_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_data', to='procurement01.rfp_skus')),
            ],
        ),
    ]
