# Generated by Django 4.2.16 on 2024-11-28 21:04


from django.db import migrations, models
import json

def migrate_extra_data(apps, schema_editor):
    # Fetch the models dynamically
    RFP_SKUs = apps.get_model('procurement01', 'RFP_SKUs')
    RFP_SKUSpecificationData = apps.get_model('procurement01', 'RFP_SKUSpecificationData')

    # Iterate through all RFP_SKUs objects
    for rfp_sku in RFP_SKUs.objects.all():
        if rfp_sku.extra_data:
            try:
                # Parse JSON data from extra_data
                data = json.loads(rfp_sku.extra_data)
                for key, value in data.items():
                    # Create new RFP_SKUSpecificationData objects
                    RFP_SKUSpecificationData.objects.create(
                        rfp_sku=rfp_sku,
                        key=key,
                        value=value
                    )
            except json.JSONDecodeError:
                continue  # Skip invalid JSON

class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0002_rfp_skuspecificationdata'),  # Replace with the last migration
    ]

    operations = [
        migrations.RunPython(migrate_extra_data),
    ]

