# Generated by Django 3.2.25 on 2024-10-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0002_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='procurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='procurement01.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement01.company'),
        ),
    ]
