# Generated by Django 4.2.16 on 2024-12-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0004_remove_rfp_skus_extra_data'),
    ]

    operations = [

        migrations.RenameModel(
            old_name='RFP_SKUs',
            new_name='RFX_SKUs',
        ),

        migrations.RenameField(
            model_name='rfx_skus',
            old_name='rfp',
            new_name='rfx',
        ),

        migrations.RenameModel(
            old_name='RFP_SKUSpecificationData',
            new_name='RFX_SKUSpecificationData',
        ),

        migrations.RenameField(
            model_name='rfx_skuspecificationdata',
            old_name='rfp_sku',
            new_name='rfx_sku',
        ),

        migrations.RenameModel(
            old_name='RFP',
            new_name='RFX',
        ),


        migrations.RenameModel(
            old_name='RFPFile',
            new_name='RFXFile',
        ),

        migrations.RenameField(
            model_name='rfxfile',
            old_name='rfp',
            new_name='rfx',
        ),

        migrations.AlterField(
            model_name='rfxfile',
            name='file',
            field=models.FileField(upload_to='rfx_files/'),
        ),

        migrations.RenameField(
            model_name='generalquestion',
            old_name='rfp',
            new_name='rfx',
        ),

        migrations.RenameField(
            model_name='skuspecificquestion',
            old_name='rfp',
            new_name='rfx',
        ),

        migrations.RenameModel(
            old_name='RFPInvitation',
            new_name='RFXInvitation',
        ),

        migrations.RenameField(
            model_name='rfxinvitation',
            old_name='rfp',
            new_name='rfx',
        ),


        migrations.AlterField(
            model_name='rfxinvitation',
            name='supplier',
            field=models.ForeignKey(
                to='procurement01.company', 
                on_delete=models.CASCADE, 
                related_name='rfx_invitations',
            ),
        ),

        migrations.RenameField(
            model_name='supplierresponse',
            old_name='rfp',
            new_name='rfx',
        ),

        migrations.AlterField(
            model_name='generalquestionresponse',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.rfxinvitation'),
        ),
       
        
        migrations.RenameField(
            model_name='skuspecificquestionresponse',
            old_name='rfp_sku',
            new_name='rfx_sku',
        )
        
    ]


