# Generated by Django 3.2.25 on 2024-10-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0004_rfp_rfpelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFPElement',
        ),
    ]
