# Generated by Django 4.2.16 on 2024-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0005_rfxfile_rfxinvitation_rename_rfp_skus_rfx_skus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
