# Generated by Django 3.2.25 on 2024-10-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0005_delete_rfpelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('multiple_choice_options', models.TextField(blank=True, null=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_questions', to='procurement01.rfp')),
            ],
        ),
    ]
