# Generated by Django 3.2.25 on 2024-10-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0006_generalquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfp',
            name='skus',
        ),
        migrations.CreateModel(
            name='RFP_SKUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.rfp')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.sku')),
            ],
            options={
                'unique_together': {('rfp', 'sku')},
            },
        ),
    ]
