# Generated by Django 3.2.25 on 2024-10-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0007_auto_20241014_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp_skus',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rfp_skus',
            unique_together=set(),
        ),
    ]
