# Generated by Django 4.2.16 on 2024-12-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0010_alter_rfx_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfx',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfxs', to='procurement01.project'),
        ),
    ]
