# Generated by Django 4.2.16 on 2024-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0011_alter_rfx_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='oems',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='procurement01.oem'),
        ),
    ]
