# Generated by Django 5.1.2 on 2024-11-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0011_skuspecificquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='general_info_files',
            field=models.FileField(blank=True, null=True, upload_to='rfp_files/'),
        ),
    ]
