# Generated by Django 5.1.2 on 2024-11-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0012_rfp_deleted_at_rfp_general_info_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfp',
            name='general_info_files',
        ),
        migrations.CreateModel(
            name='RFPFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rfp_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='procurement01.rfp')),
            ],
        ),
    ]
