# Generated by Django 5.1.2 on 2024-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0013_remove_rfp_general_info_files_rfpfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
