# Generated by Django 4.2.16 on 2024-12-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0014_sku_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rfxs', to='procurement01.company'),
            preserve_default=False,
        ),
    ]
