# Generated by Django 5.1.2 on 2024-11-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0016_rfpinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='procurement01.rfp')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.company')),
            ],
        ),
        migrations.CreateModel(
            name='SKUSpecificQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='responses/files/')),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.skuspecificquestion')),
                ('rfp_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.rfp_skus')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_question_responses', to='procurement01.supplierresponse')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='responses/files/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement01.generalquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_responses', to='procurement01.supplierresponse')),
            ],
        ),
    ]
