# Generated by Django 5.1.2 on 2024-11-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0017_supplierresponse_skuspecificquestionresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalquestionresponse',
            name='invitation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='procurement01.rfpinvitation'),
            preserve_default=False,
        ),
    ]
