# Generated by Django 5.1.2 on 2024-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement01', '0018_generalquestionresponse_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuspecificquestionresponse',
            name='answer_choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalquestionresponse',
            name='answer_choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skuspecificquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File Upload'), ('date', 'Date'), ('Single-select', 'Single-select'), ('Multi-select', 'Multi-select')], max_length=50),
        ),
    ]
